/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Demo for webhook
package simple_java;
import java.sql.Timestamp;

public class App {
    public String getGreeting() {
        return "Hello Gradle V2!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        System.out.println(timestamp);
    }
}
